/*
let employee_data=[{"id":1,"name":"Noelani","email":"npavlovsky0@merriam-webster.com"},
{"id":2,"name":"Myrvyn","email":"mlote1@oakley.com"},
{"id":3,"name":"Kristos","email":"kswetman2@flavors.me"},
{"id":4,"name":"Bee","email":"bbrahms3@exblog.jp"},
{"id":5,"name":"Mortimer","email":"mwasling4@1688.com"},
{"id":6,"name":"Eden","email":"eflatt5@craigslist.org"},
{"id":7,"name":"Lorrin","email":"ltedridge6@mail.ru"},
{"id":8,"name":"Gideon","email":"gmoriarty7@mozilla.com"},
{"id":9,"name":"Kalle","email":"ksucre8@desdev.cn"},
{"id":10,"name":"Darill","email":"dclaypoole9@qq.com"},
{"id":11,"name":"Seumas","email":"scrowcha@cbsnews.com"},
{"id":12,"name":"Mabelle","email":"mmewhirterb@abc.net.au"},
{"id":13,"name":"Ruggiero","email":"rdangerfieldc@msu.edu"},
{"id":14,"name":"Jacquette","email":"judied@1688.com"},
{"id":15,"name":"Eleen","email":"espurryere@aboutads.info"},
{"id":16,"name":"Dex","email":"dgergerf@ucoz.ru"},
{"id":17,"name":"Piotr","email":"pnattrassg@blogger.com"},
{"id":18,"name":"Ned","email":"nhouldenh@ovh.net"},
{"id":19,"name":"Marshal","email":"mzukeri@drupal.org"},
{"id":20,"name":"Mayor","email":"mromushkinj@salon.com"},
{"id":21,"name":"Belinda","email":"bkermitk@cdbaby.com"},
{"id":22,"name":"Lanni","email":"lbuttrissl@zimbio.com"},
{"id":23,"name":"Morry","email":"mplaicem@merriam-webster.com"},
{"id":24,"name":"Cherida","email":"cmcentagartn@exblog.jp"},
{"id":25,"name":"Daniel","email":"deretto@rakuten.co.jp"},
{"id":26,"name":"Becka","email":"bdenacampp@hhs.gov"},
{"id":27,"name":"Vergil","email":"vdarkq@behance.net"},
{"id":28,"name":"Reggie","email":"rmacsweeneyr@cdbaby.com"},
{"id":29,"name":"Ninon","email":"nflintofts@yandex.ru"},
{"id":30,"name":"Con","email":"ccrookst@php.net"},
{"id":31,"name":"Daniele","email":"dshilstonu@wisc.edu"},
{"id":32,"name":"Alex","email":"aquigv@github.io"},
{"id":33,"name":"Halette","email":"hmcalpinew@dailymail.co.uk"},
{"id":34,"name":"Ibrahim","email":"iphilliphsx@fastcompany.com"},
{"id":35,"name":"Bing","email":"bconrardy@booking.com"},
{"id":36,"name":"Westleigh","email":"wwattingz@toplist.cz"},
{"id":37,"name":"Benni","email":"bhamlet10@friendfeed.com"},
{"id":38,"name":"Eydie","email":"eprobets11@sbwire.com"},
{"id":39,"name":"Adel","email":"azimek12@g.co"},
{"id":40,"name":"Livia","email":"lzollner13@ameblo.jp"},
{"id":41,"name":"Dunn","email":"dcarcass14@eventbrite.com"},
{"id":42,"name":"Aindrea","email":"adantoni15@reuters.com"},
{"id":43,"name":"Karly","email":"kteesdale16@behance.net"},
{"id":44,"name":"Lazare","email":"lpetracci17@tiny.cc"},
{"id":45,"name":"Chlo","email":"cmanchester18@google.nl"},
{"id":46,"name":"Bellina","email":"bgencke19@npr.org"},
{"id":47,"name":"Fidela","email":"fdowson1a@hud.gov"},
{"id":48,"name":"Babs","email":"bdabnor1b@foxnews.com"},
{"id":49,"name":"Care","email":"cveness1c@hao123.com"},
{"id":50,"name":"Fawn","email":"fkynder1d@ow.ly"},
{"id":51,"name":"Rene","email":"rmaty1e@sfgate.com"},
{"id":52,"name":"Dillon","email":"dwilleson1f@google.cn"},
{"id":53,"name":"Adel","email":"alimeburn1g@netscape.com"},
{"id":54,"name":"Ber","email":"bsenton1h@cisco.com"},
{"id":55,"name":"Cointon","email":"ckincaid1i@pagesperso-orange.fr"},
{"id":56,"name":"Zarla","email":"zrampley1j@sakura.ne.jp"},
{"id":57,"name":"Domini","email":"despadater1k@geocities.jp"},
{"id":58,"name":"Franzen","email":"fmeace1l@addtoany.com"},
{"id":59,"name":"Glennis","email":"ghenrique1m@reference.com"},
{"id":60,"name":"Bevan","email":"bnisard1n@oracle.com"},
{"id":61,"name":"Malachi","email":"mhalksworth1o@oaic.gov.au"},
{"id":62,"name":"Barthel","email":"bgeorgeot1p@nba.com"},
{"id":63,"name":"Cecilla","email":"claraway1q@skyrock.com"},
{"id":64,"name":"Liza","email":"ljenkins1r@deviantart.com"},
{"id":65,"name":"Chrissie","email":"cbruneton1s@wiley.com"},
{"id":66,"name":"Jamie","email":"jspencelayh1t@creativecommons.org"},
{"id":67,"name":"Nick","email":"nbockin1u@mashable.com"},
{"id":68,"name":"Derron","email":"dhext1v@mysql.com"},
{"id":69,"name":"Randie","email":"rdallicott1w@youku.com"},
{"id":70,"name":"Maurine","email":"mpiddlehinton1x@gizmodo.com"},
{"id":71,"name":"Brita","email":"bearley1y@meetup.com"},
{"id":72,"name":"Isidoro","email":"ichat1z@hibu.com"},
{"id":73,"name":"Addy","email":"ajohnsey20@topsy.com"},
{"id":74,"name":"Caty","email":"csisnett21@webmd.com"},
{"id":75,"name":"Ashlan","email":"abarnhart22@webs.com"},
{"id":76,"name":"Rubin","email":"raloshkin23@wiley.com"},
{"id":77,"name":"Aggy","email":"anorthwood24@ted.com"},
{"id":78,"name":"Jorie","email":"jhuxtable25@youtube.com"},
{"id":79,"name":"Gary","email":"gdurling26@epa.gov"},
{"id":80,"name":"Prisca","email":"pmalpass27@sogou.com"},
{"id":81,"name":"Camellia","email":"cmcclancy28@hatena.ne.jp"},
{"id":82,"name":"Eduino","email":"eisted29@ycombinator.com"},
{"id":83,"name":"Sybila","email":"seyes2a@biblegateway.com"},
{"id":84,"name":"Marin","email":"mbrake2b@free.fr"},
{"id":85,"name":"Allayne","email":"abradder2c@patch.com"},
{"id":86,"name":"Maryann","email":"mmulhall2d@fotki.com"},
{"id":87,"name":"Kellia","email":"ksiverns2e@phpbb.com"},
{"id":88,"name":"Bernie","email":"bscriver2f@chronoengine.com"},
{"id":89,"name":"Gerry","email":"gtitterell2g@admin.ch"},
{"id":90,"name":"Ricard","email":"rtender2h@ft.com"},
{"id":91,"name":"Atlanta","email":"alob2i@reuters.com"},
{"id":92,"name":"Daniele","email":"djecock2j@unblog.fr"},
{"id":93,"name":"Adriaens","email":"adonaldson2k@sakura.ne.jp"},
{"id":94,"name":"Remus","email":"rgunby2l@jiathis.com"},
{"id":95,"name":"Giffy","email":"gdundendale2m@theguardian.com"},
{"id":96,"name":"Gil","email":"gwhelband2n@nationalgeographic.com"},
{"id":97,"name":"Eleonora","email":"ecleve2o@ucoz.com"},
{"id":98,"name":"Aubrey","email":"amains2p@gizmodo.com"},
{"id":99,"name":"Gilburt","email":"grikard2q@amazonaws.com"},
{"id":100,"name":"Gene","email":"gmacallaster2r@spiegel.de"}]

function emp_data() {
    rows=""
    for(let i=0; i<=employee_data.length-1; i++){

        rows=rows + `<tr>

        <td> ${employee_data[i].id}</td>
        <td> ${employee_data[i].name}</td>
        <td> ${employee_data[i].email}</td>
        </tr>`
    }
document.getElementById("abc").innerHTML=rows
}*/


let employees=[{"id":1,"name":"Noelani","email":"npavlovsky0@merriam-webster.com"},
{"id":2,"name":"Myrvyn","email":"mlote1@oakley.com"},
{"id":3,"name":"Kristos","email":"kswetman2@flavors.me"},
{"id":4,"name":"Bee","email":"bbrahms3@exblog.jp"},
{"id":5,"name":"Mortimer","email":"mwasling4@1688.com"},
{"id":6,"name":"Eden","email":"eflatt5@craigslist.org"},
{"id":7,"name":"Lorrin","email":"ltedridge6@mail.ru"},
{"id":8,"name":"Gideon","email":"gmoriarty7@mozilla.com"},
{"id":9,"name":"Kalle","email":"ksucre8@desdev.cn"},
{"id":10,"name":"Darill","email":"dclaypoole9@qq.com"},
{"id":11,"name":"Seumas","email":"scrowcha@cbsnews.com"},
{"id":12,"name":"Mabelle","email":"mmewhirterb@abc.net.au"},
{"id":13,"name":"Ruggiero","email":"rdangerfieldc@msu.edu"},
{"id":14,"name":"Jacquette","email":"judied@1688.com"},
{"id":15,"name":"Eleen","email":"espurryere@aboutads.info"},
{"id":16,"name":"Dex","email":"dgergerf@ucoz.ru"},
{"id":17,"name":"Piotr","email":"pnattrassg@blogger.com"},
{"id":18,"name":"Ned","email":"nhouldenh@ovh.net"},
{"id":19,"name":"Marshal","email":"mzukeri@drupal.org"},
{"id":20,"name":"Mayor","email":"mromushkinj@salon.com"},
{"id":21,"name":"Belinda","email":"bkermitk@cdbaby.com"},
{"id":22,"name":"Lanni","email":"lbuttrissl@zimbio.com"},
{"id":23,"name":"Morry","email":"mplaicem@merriam-webster.com"},
{"id":24,"name":"Cherida","email":"cmcentagartn@exblog.jp"},
{"id":25,"name":"Daniel","email":"deretto@rakuten.co.jp"},
{"id":26,"name":"Becka","email":"bdenacampp@hhs.gov"},
{"id":27,"name":"Vergil","email":"vdarkq@behance.net"},
{"id":28,"name":"Reggie","email":"rmacsweeneyr@cdbaby.com"},
{"id":29,"name":"Ninon","email":"nflintofts@yandex.ru"},
{"id":30,"name":"Con","email":"ccrookst@php.net"},
{"id":31,"name":"Daniele","email":"dshilstonu@wisc.edu"},
{"id":32,"name":"Alex","email":"aquigv@github.io"},
{"id":33,"name":"Halette","email":"hmcalpinew@dailymail.co.uk"},
{"id":34,"name":"Ibrahim","email":"iphilliphsx@fastcompany.com"},
{"id":35,"name":"Bing","email":"bconrardy@booking.com"},
{"id":36,"name":"Westleigh","email":"wwattingz@toplist.cz"},
{"id":37,"name":"Benni","email":"bhamlet10@friendfeed.com"},
{"id":38,"name":"Eydie","email":"eprobets11@sbwire.com"},
{"id":39,"name":"Adel","email":"azimek12@g.co"},
{"id":40,"name":"Livia","email":"lzollner13@ameblo.jp"},
{"id":41,"name":"Dunn","email":"dcarcass14@eventbrite.com"},
{"id":42,"name":"Aindrea","email":"adantoni15@reuters.com"},
{"id":43,"name":"Karly","email":"kteesdale16@behance.net"},
{"id":44,"name":"Lazare","email":"lpetracci17@tiny.cc"},
{"id":45,"name":"Chlo","email":"cmanchester18@google.nl"},
{"id":46,"name":"Bellina","email":"bgencke19@npr.org"},
{"id":47,"name":"Fidela","email":"fdowson1a@hud.gov"},
{"id":48,"name":"Babs","email":"bdabnor1b@foxnews.com"},
{"id":49,"name":"Care","email":"cveness1c@hao123.com"},
{"id":50,"name":"Fawn","email":"fkynder1d@ow.ly"},
{"id":51,"name":"Rene","email":"rmaty1e@sfgate.com"},
{"id":52,"name":"Dillon","email":"dwilleson1f@google.cn"},
{"id":53,"name":"Adel","email":"alimeburn1g@netscape.com"},
{"id":54,"name":"Ber","email":"bsenton1h@cisco.com"},
{"id":55,"name":"Cointon","email":"ckincaid1i@pagesperso-orange.fr"},
{"id":56,"name":"Zarla","email":"zrampley1j@sakura.ne.jp"},
{"id":57,"name":"Domini","email":"despadater1k@geocities.jp"},
{"id":58,"name":"Franzen","email":"fmeace1l@addtoany.com"},
{"id":59,"name":"Glennis","email":"ghenrique1m@reference.com"},
{"id":60,"name":"Bevan","email":"bnisard1n@oracle.com"},
{"id":61,"name":"Malachi","email":"mhalksworth1o@oaic.gov.au"},
{"id":62,"name":"Barthel","email":"bgeorgeot1p@nba.com"},
{"id":63,"name":"Cecilla","email":"claraway1q@skyrock.com"},
{"id":64,"name":"Liza","email":"ljenkins1r@deviantart.com"},
{"id":65,"name":"Chrissie","email":"cbruneton1s@wiley.com"},
{"id":66,"name":"Jamie","email":"jspencelayh1t@creativecommons.org"},
{"id":67,"name":"Nick","email":"nbockin1u@mashable.com"},
{"id":68,"name":"Derron","email":"dhext1v@mysql.com"},
{"id":69,"name":"Randie","email":"rdallicott1w@youku.com"},
{"id":70,"name":"Maurine","email":"mpiddlehinton1x@gizmodo.com"},
{"id":71,"name":"Brita","email":"bearley1y@meetup.com"},
{"id":72,"name":"Isidoro","email":"ichat1z@hibu.com"},
{"id":73,"name":"Addy","email":"ajohnsey20@topsy.com"},
{"id":74,"name":"Caty","email":"csisnett21@webmd.com"},
{"id":75,"name":"Ashlan","email":"abarnhart22@webs.com"},
{"id":76,"name":"Rubin","email":"raloshkin23@wiley.com"},
{"id":77,"name":"Aggy","email":"anorthwood24@ted.com"},
{"id":78,"name":"Jorie","email":"jhuxtable25@youtube.com"},
{"id":79,"name":"Gary","email":"gdurling26@epa.gov"},
{"id":80,"name":"Prisca","email":"pmalpass27@sogou.com"},
{"id":81,"name":"Camellia","email":"cmcclancy28@hatena.ne.jp"},
{"id":82,"name":"Eduino","email":"eisted29@ycombinator.com"},
{"id":83,"name":"Sybila","email":"seyes2a@biblegateway.com"},
{"id":84,"name":"Marin","email":"mbrake2b@free.fr"},
{"id":85,"name":"Allayne","email":"abradder2c@patch.com"},
{"id":86,"name":"Maryann","email":"mmulhall2d@fotki.com"},
{"id":87,"name":"Kellia","email":"ksiverns2e@phpbb.com"},
{"id":88,"name":"Bernie","email":"bscriver2f@chronoengine.com"},
{"id":89,"name":"Gerry","email":"gtitterell2g@admin.ch"},
{"id":90,"name":"Ricard","email":"rtender2h@ft.com"},
{"id":91,"name":"Atlanta","email":"alob2i@reuters.com"},
{"id":92,"name":"Daniele","email":"djecock2j@unblog.fr"},
{"id":93,"name":"Adriaens","email":"adonaldson2k@sakura.ne.jp"},
{"id":94,"name":"Remus","email":"rgunby2l@jiathis.com"},
{"id":95,"name":"Giffy","email":"gdundendale2m@theguardian.com"},
{"id":96,"name":"Gil","email":"gwhelband2n@nationalgeographic.com"},
{"id":97,"name":"Eleonora","email":"ecleve2o@ucoz.com"},
{"id":98,"name":"Aubrey","email":"amains2p@gizmodo.com"},
{"id":99,"name":"Gilburt","email":"grikard2q@amazonaws.com"},
{"id":100,"name":"Gene","email":"gmacallaster2r@spiegel.de"}]

function get_employee() {
    let rows=""
    for( emp of employees){

       rows=rows+ `<tr>

        <td>${emp.id}</td>
        <td>${emp.name}</td>
        <td>${emp.email}</td>
        </tr>`
    }
    document.getElementById("123").innerHTML=rows
    
}

    
